jenkins-x-plugins/jx-secret

- .golangci.yml
- cmd/docs/main.go
- cmd/docs/man_docs.go
- cmd/docs/md_docs.go
- hack/linter.sh
- jenkins-x.yml
- pkg/cmd/edit/edit.go
- pkg/cmd/export/export.go
- pkg/cmd/import/import.go
- pkg/cmd/plugins/plugins.go
- pkg/cmd/plugins/upgrade/upgrade.go
- pkg/cmd/version/version.go
- pkg/extsecrets/client.go
- pkg/extsecrets/editor/vault/vault_editor.go
- pkg/extsecrets/helpers.go
- pkg/plugins/helpers_test.go
> chore: enable golangci-lint

- go.mod
- pkg/cmd/edit/edit_test.go
- pkg/cmd/export/export_test.go
- pkg/cmd/import/import.go
- pkg/cmd/import/import_test.go
- pkg/cmd/populate/populate_test.go
- pkg/cmd/vault/portforward/vault_portforward_test.go
- pkg/cmd/vault/wait/vault_wait.go
- pkg/cmd/vault/wait/vault_wait_test.go
- pkg/cmd/verify/verify_test.go
- pkg/extsecrets/helpers.go
- pkg/extsecrets/secretfacade/load.go
- pkg/schema/generators/secret_entry.go
we were not defaulting the namespace if its not specified. refactored to reuse the jx-helpers method which defaults missing namespaces
> fix: some bugs in secret population

- pkg/schema/generators/secret_entry.go
> fix: add more logging to secret step

- pkg/cmd/edit/edit.go
- pkg/cmd/edit/edit_test.go
- pkg/cmd/import/import.go
- pkg/cmd/populate/populate.go
- pkg/cmd/root.go
- pkg/cmd/verify/verify.go
- pkg/cmd/wait/test_data/knative-docker-user-pass.yaml
- pkg/cmd/wait/test_data/lighthouse-oauth-token.yaml
- pkg/cmd/wait/wait.go
- pkg/cmd/wait/wait_test.go
- pkg/extsecrets/constants.go
- pkg/extsecrets/editor/gsm/gsm_editor.go
- pkg/extsecrets/editor/interface.go
- pkg/extsecrets/editor/vault/vault_editor.go
- pkg/extsecrets/secretfacade/types.go
- pkg/extsecrets/secretfacade/verify.go
> fix: add wait function and better edit

- pkg/cmd/wait/wait.go
and avoid too much noise on waiting for ExternalSecrets
> fix: timeout config bug

- pkg/cmd/vault/portforward/vault_portforward.go
- pkg/cmd/vault/wait/vault_wait.go
- pkg/cmd/vault/wait/vault_wait_test.go
- pkg/cmd/wait/wait.go
- pkg/extsecrets/editor/vault/vault_editor.go
- pkg/extsecrets/editor/vault/vault_editor_test.go
also avoid logging the passwords/tokens when using vault
> fix: add better waiting logic for vault

- README.md
- pkg/apis/external/v1/types.go
- pkg/cmd/convert/convert.go
- pkg/cmd/convert/test_data/simple/stringData/expected.yaml
- pkg/cmd/convert/test_data/simple/stringData/source.yaml
- pkg/cmd/verify/verify.go
- pkg/cmd/wait/wait.go
to work well with bucketrepo chart
> fix: handle stringData secrets

- jenkins-x.yml
> fix: release pipeline

- pkg/cmd/verify/verify.go
- pkg/extsecrets/secretfacade/load.go
> fix: handle multiple namespaces better

- pkg/cmd/populate/populate.go
- pkg/cmd/populate/templater.go
- pkg/cmd/populate/templatertesting/run.go
> fix: handle all namespaces better

- pkg/apis/mapping/v1alpha1/types.go
- pkg/cmd/convert/convert.go
> fix: improve local secret support

- pkg/extsecrets/editor/local/local_editor.go
- pkg/extsecrets/editor/local/local_editor_test.go
> fix: for local secret population

- jenkins-x.yml
Signed-off-by: jstrachan <jenkins-x@googlegroups.com>
> fix: creates resources

- .goreleaser.yml
> fix: fix issue with missing version info in binary

- go.mod
- go.sum
- pkg/cmd/replicate/replicate.go
Signed-off-by: jstrachan <james.strachan@gmail.com>
> fix: add better filtering of replicate

- pkg/cmd/populate/populate.go
- pkg/cmd/replicate/replicate.go
- pkg/cmd/replicate/replicate_test.go
- pkg/extsecrets/constants.go
- pkg/extsecrets/editor/local/local_editor.go
- pkg/extsecrets/editor/local/local_editor_test.go
Signed-off-by: jstrachan <james.strachan@gmail.com>
> fix: for local secret replicatino

- Dockerfile.preview
- go.mod
- go.sum
- pkg/cmd/populate/test_data/jx-requirements.yml
This reverts commit cc99deee2d0900230d67803e7e58b13f457f1a81.
> fix: revert "Merge pull request #71 from chrismellard/azure-secret-key-vault"

- Makefile
> fix: avoid building linux binary twice

- go.mod
- pkg/cmd/populate/functions.go
- pkg/cmd/populate/templater.go
- pkg/cmd/populate/templater_test.go
- pkg/cmd/populate/templatertesting/run.go
- pkg/cmd/populate/templatertesting/types.go
- pkg/cmd/populate/test_data/secret-schema.yaml
- pkg/cmd/populate/test_data/secrets/jx-basic-auth-htpasswd.yaml
> fix: add htpasswdSecret function

- pkg/masker/dump/main.go
- pkg/masker/masker.go
- pkg/masker/masker_test.go
> fix: add secret masker

- pkg/apis/schema/v1alpha1/types.go
- pkg/cmd/populate/templater.go
- pkg/masker/masker.go
- pkg/masker/watcher/watcher.go
- pkg/masker/watcher/watcher_test.go
so that we can mark fields as being excluded from the masking (e.g. for
usernames we are happy to appear in logs)
> fix: improve the masker logic

- pkg/masker/watcher/watcher.go
> fix: add helper method

- pkg/masker/masker.go
- pkg/masker/watcher/watcher.go
as we only want to see in the logs actual changes to masking
> fix: improve output when using watcher

- pkg/cmd/populate/templater.go
to avoid stopping first time - the next secret generation loop we will populate it
> fix: return blank string if we can't create htpasswd

- go.sum
- pkg/cmd/convert/convert.go
- pkg/cmd/convert/convert_test.go
- pkg/cmd/convert/test_data/schema/config-root/namespaces/jx/tekton/webhook-certs-secret.yaml
> fix: lets not convert empty Secret resources to ExternalSecrets by default

- pkg/cmd/populate/populate.go
- pkg/extsecrets/editor/gsm/gsm_editor.go
> fix: allow a side car to be used if enabled with env vars

- pkg/extsecrets/editor/gsm/gsm_editor.go
so we can share content between the boot container and the secret sidecar
> fix: support an optional temp dir for secrets

- pkg/cmd/convert/convert.go
This allows us to ensure that folks can have different secrets for different namespaces
> fix: add a prefix to vault mappings

- pkg/cmd/populate/populate.go
- pkg/cmd/populate/populate_test.go
> fix: added in vault auth configuration for jx secret populate

- go.mod
- go.sum
- pkg/cmd/populate/populate.go
> fix: add fix for local secrets and annotations + type

- pkg/cmd/edit/edit.go
- pkg/extsecrets/editor/gsm/gsm_editor.go
This causes a big delay and confision to users otherwise
> chore: only verify gcloud is installed once rather than for every external secret

- go.mod
- go.sum
- pkg/cmd/populate/templater.go
- pkg/schemas/generators/secret_entry.go
lets use debug logging for stuff that happens all the time
> fix: tone down logging

- go.mod
- go.sum
- pkg/cmd/edit/edit.go
- pkg/cmd/populate/populate.go
- pkg/cmd/populate/populate_test.go
- pkg/cmd/populate/test_data/populate_helm_secrets/extsecrets/lighthouse-oauth-token.yaml
- pkg/cmd/populate/test_data/populate_helm_secrets/fake-helm-secrets/jx/lighthouse-oauth-token.yaml
- pkg/cmd/populate/test_data/populate_helm_secrets/jx-requirements.yml
with defaults from the helm template Secret resources if there is no explicit generator/default/template
also add interactive secret editing to improve the UX
> fix: add automatic population of external secret stores

- pkg/cmd/populate/templater.go
this avoids a slow retry loop when populating the basic auth user/pwd
Signed-off-by: jenkins-x-test-bot <jenkins-x@googlegroups.com>
> fix: avoid retry loop when using local secrets

- pkg/cmd/populate/templater.go
- pkg/cmd/populate/templatertesting/run.go
- pkg/cmd/populate/templatertesting/types.go
> chore: improve the test framework

- pkg/cmd/populate/populate_test.go
- pkg/cmd/populate/templater.go
- pkg/cmd/populate/test_data/load_requirements/jx-requirements.yml
- pkg/extsecrets/editor/gsm/gsm_editor.go
> chore: add better error reporting if we fail to parse GSM secret

- pkg/cmd/vault/shell/shell.go
Apart from making it possible to run a shell at all I made it easier to give a different command with arguments. Instead of
`jx secret vault shell -s vault --args kv --args get --args secret/jx/mavenSettings`
you can do
`jx secret vault shell vault kv  get secret/jx/mavenSettings`
Fixes: #340
> fix: Make vault shell command work

- pkg/cmd/populate/populate.go
Always use Key Value style even if secret length is one
> fix: parse all secrets as k/v

- Dockerfile.preview
- pkg/cmd/populate/populate.go
> fix: use EXTERNAL_VAULT to toggle vault creation

- pkg/cmd/populate/populate.go
- pkg/plugins/versions.go
> refactor: upgrade vault to 1.8.3

- .golangci.yml
- pkg/cmd/edit/edit.go
- pkg/extsecrets/editor/factory/factory.go
> fix: make jx secret edit work with external vault

- go.mod
- go.sum
Also ran go mod tidy
Fixes that jx secret removes issueProvider from jx-requirements.yaml
> chore: Upgrade dependency on github.com/jenkins-x/jx-api/v4

- .lighthouse/jenkins-x/lint.yaml
- .lighthouse/jenkins-x/triggers.yaml
- .sonarcloud.properties
- OWNERS
- pkg/apis/mapping/v1alpha1/types.go
- pkg/cmd/convert/convert.go
- pkg/cmd/convert/convert_test.go
- pkg/cmd/convert/edit/edit.go
- pkg/cmd/convert/edit/edit_test.go
- pkg/cmd/convert/edit/test_data/asm_defaults_add/.jx/secret/mapping/secret-mappings.yaml
- pkg/cmd/convert/edit/test_data/asm_defaults_add/jx-requirements.yml
- pkg/cmd/convert/test_data/awsSecretsManager/.jx/secret/mapping/secret-mappings.yaml
- pkg/cmd/convert/test_data/awsSecretsManager/oauth1/expected.yaml
- pkg/extsecrets/helpers_test.go
> fix: get region for asm secrets from requirements file

- Makefile
Adding the make target to build on the m1 mac.
> Adding make target for darwin arm64

- .lighthouse/jenkins-x/lint.yaml
- .lighthouse/jenkins-x/pullrequest.yaml
> fix: remove resource request from step template

- OWNERS
- OWNERS_ALIASES
- cmd/docs/main.go
- pkg/apis/mapping/v1alpha1/types.go
- pkg/cmd/convert/convert_test.go
- pkg/cmd/convert/edit/edit_test.go
- pkg/cmd/populate/populate_test.go
- pkg/cmd/populate/templatertesting/run.go
- pkg/cmd/replicate/replicate_test.go
- pkg/cmd/vault/wait/vault_wait_test.go
- pkg/extsecrets/testsecrets/load.go
- pkg/plugins/versions.go
- pkg/schemas/helpers.go
- pkg/schematests/validation_test.go
- pkg/secretmapping/helpers.go
- pkg/vaults/vaultcli/helpers.go
- pkg/vaults/vaultcli/wait.go
fixes https://github.com/jenkins-x/jx/issues/8257
> feat: upgrade vault cli to 1.10.4

- go.mod
Signed-off-by: PratikforCoding <kotalpratik@gmail.com>
> Updated go version to 1.19 in make file of jx-secret

- go.mod
- go.sum
Auto PR failing as `go mod tidy` required.
AutoPR: https://github.com/jenkins-x-plugins/jx-secret/pull/413
> chore(deps): update secret-facade
